language: node_js
node_js:
  - "node"
install: npm install
notifications:
  email:
    recipients:
      - stob@hs-furtwangen.de # Achtung: Diese E-Mail Adresse durch eigene ersetzen!
    on_success: never
    on_failure: always
